name: Run mobsfscan scan

on:
  workflow_dispatch:
  push:

  
jobs:
  build:
    runs-on: moose-1
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Checkout mobsfscan repo
        uses: actions/checkout@v2
        with:
          repository: MobSF/mobsfscan
          path: mobsfscan

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
         python-version: '3.9.1'
         
      - name: Install dependencies
        run: |
          ls -la
          python -m pip install --upgrade pip
          pip install setuptools wheel twine mobsfscan/

         
      - name: Run mobsfscan
        run: |
          mobsfscan --sarif --output results.sarif .
          
      - name: Upload mobsfscan report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
