name: Run Script

on:
  workflow_dispatch:
  push:

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout mobsfscan repo
        uses: actions/checkout@v2
        with:
          repository: MobSF/mobsfscan

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
         python-version: '3.x'
         
      - name: Install dependencies
        run: |
          ls -la
          python -m pip install --upgrade pip
          pip install setuptools wheel twine .

         
      - name: Run mobsfscan
        run: |
          cd ../iGoat*/; pwd; ls -la; mobsfscan --sarif --output results.sarif .
          
      - name: Upload mobsfscan report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
